### ISSUE TITLE
强烈建议优先提供mac版本

### ISSUE THREAD

**Issue by RadianceL** [fordes123/subtitles-view#2]
个人觉得开发百分之90都是mac用户吧，需要协助的话我可以周末帮忙适配一下

**Comment by fordes123** [comment]
说来惭愧不太熟悉mac平台，我的打算是先完善功能，毕竟现在还很简陋。
如果你有兴趣的话欢迎fork，对于mac平台，我认为自己还需要学习，可能短期内不会考虑适配
