### ISSUE TITLE
代码不全，inputset缺少videoFile

### ISSUE THREAD

**Issue by WuXiaoYang1** [fordes123/subtitles-view#5]
![image](https://user-images.githubusercontent.com/52439052/108582479-afebe000-736e-11eb-80c3-f9ebe358bff6.png)
![image](https://user-images.githubusercontent.com/52439052/108582487-baa67500-736e-11eb-95fb-145ed9692cd6.png)

**Comment by WuXiaoYang1** [comment]
是这几个文件已经废弃了吗？

**Comment by fordes123** [comment]
> 是这几个文件已经废弃了吗？

准确说是整个都废弃掉了，项目重写，将于近期更新
