### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by GBEYOND0613** [fordes123/subtitles-view#6]
版本：Subtitles-View 1.1.0.Alpha
问题一：在没有安装Java se 的电脑上可以运行，但是在安装了Java的电脑上没法打开（自学Java网课，英文的课）
问题二：readme.md中链接无法打开

**Comment by fordes123** [comment]
1. 程序优先使用本地java环境，而后使用内置jar，请确认本地java版本(1.8)以及环境变量是否正确配置
2. 相关链接已经修复
