### ISSUE TITLE
编译不了。

### ISSUE THREAD

**Issue by linuxxx** [fordes123/subtitles-view#9]
![image](https://user-images.githubusercontent.com/2128377/129432652-3c5175f9-e94c-4d7a-8ac0-32a359bad2de.png)

缺少包

自带的jar包里面没有这个cpdb
![image](https://user-images.githubusercontent.com/2128377/129432659-3304980d-112c-4fb3-bab0-c44aa71e4974.png)

**Comment by fordes123** [comment]
历史代码弃用，已经重构，后续将通过http方式进行调用
